jobs:
  build:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - run:
          name: Simple Copy and cat
          command: |
            ls -al
            echo "now copying files"
            mv work.txt play.txt
            ls -al
            cat play.txt
            echo '^^^all done now^^^'